version: '2.3'
services:
  kalki-dashboard:
    image: kalki/kalki-dashboard
    container_name: kalki-dashboard
    network_mode: "host"
    stdin_open: true
    tty: true
    environment:
      - TZ=${HOST_TZ}
